apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  namespace : monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/alertmanager/metrics'
spec:
  selector:
    app: prometheus-alertmanager
  #type: NodePort
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
