apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace : monitoring
data:
  alert.rules: |-
    ALERT HighCPU
      IF up == 0
      FOR 1m
      LABELS { service = "page" }
      ANNOTATIONS {
        summary = "Instance {{$labels.host}} is down",
        description = "{{$labels.host}} of job {{$labels.job}} has been down for more than 1 minutes",
      }

