apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-monitoring
  namespace : monitoring
  labels:
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-monitoring
    spec:

      containers:
      # Prometheus server
      - name: prometheus
        image: prom/prometheus:v1.3.1
        args:
          - '-storage.local.retention=72h'
          - '-storage.local.path=/mnt/azure/'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-alertmanager.url=http://alertmanager-svc:9093'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume-prometheus
          mountPath: /etc/prometheus
        - name: config-volume-alert-rules
          mountPath: /etc/prometheus-rules
        - name: azure
          mountPath: /mnt/azure/
        - name: prometheus-data
          mountPath: /home
      volumes:
      - name: config-volume-prometheus
        configMap:
          name: prometheus
      - name: config-volume-alert-rules
        configMap:
          name: prometheus-alert-rules
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: k8stest
          readOnly: false
      - name: prometheus-data
        emptyDir: {}
